name: navigation_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3  # Add this line

flutter_icons:
  android: true
  ios: true
  image_path: "asset/images/1.jpg"  # The path to your launcher icon

flutter:
  uses-material-design: true
  assets:
    - asset/images/1.jpg
    - asset/background_texture.png